<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>impex</string>
	</array>
	<key>name</key>
	<string>hybrisImPex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>INSERT_UPDATE|UPDATE|INSERT|REMOVE</string>
			<key>name</key>
			<string>keyword.control.impex</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>^#.+$|^$</string>
			<key>name</key>
			<string>comment.line.impex</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>input values</string>
			<key>match</key>
			<string>^;.+$</string>
			<key>name</key>
			<string>entity.name.function.impex</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variables</string>
			<key>match</key>
			<string>^\$.+(?==)</string>
			<key>name</key>
			<string>constant.character.impex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"\#\%</string>
			<key>name</key>
			<string>variable.parameter.impex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.impex</string>
	<key>uuid</key>
	<string>2eb80721-41c7-46e8-be19-f8333601c9be</string>
</dict>
</plist>
